# Generated by Django 5.2.5 on 2025-10-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('current_job', models.CharField(max_length=50)),
                ('applied_job', models.CharField(max_length=200)),
                ('passport_number', models.IntegerField()),
                ('picture', models.ImageField(upload_to='app/static/users')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
