# Generated by Django 5.2.5 on 2025-10-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_users_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='passport_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
