# Generated by Django 5.2.5 on 2025-10-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_users_passport_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='picture',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
        migrations.RemoveField(
            model_name='users',
            name='applied_job',
        ),
        migrations.RemoveField(
            model_name='users',
            name='current_job',
        ),
        migrations.RemoveField(
            model_name='users',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='users',
            name='passport_number',
        ),
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
