# Generated by Django 5.2.5 on 2025-10-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_picture_users_photo_remove_users_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='bio',
            field=models.CharField(blank=True, null=True),
        ),
    ]
